djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('register/', views.registerUser, name="register"),
    path('account/', views.userAccount, name="account"),
    path('edit-account/', views.editSettings, name="edit-account"),
    path('', views.homePage, name='index'),
]

users/models.py
from django.core.validators import RegexValidator
from phonenumber_field.modelfields import PhoneNumberField
from django.db import models
from django.contrib.auth.models import User
import uuid


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True)
    id = models.UUIDField(default=uuid.uuid4, unique=True, primary_key=True, editable=False)
    username = models.CharField(max_length=200, blank=True, null=True, verbose_name='Имя на сайте')
    profile_image = models.ImageField(
        null=True, blank=True, upload_to='profiles/', default="profiles/user-default.png")
    profile_image_border = models.ImageField(null=True, blank=True, upload_to='profiles/', default="profile/border/user"
                                                                                                   "-default.png")
    name = models.CharField(max_length=200, blank=True, null=True, verbose_name='Имя')
    secondName = models.CharField(max_length=200, blank=True, null=True, verbose_name='Фамилия')
    lastName = models.CharField(max_length=200, blank=True, null=True, verbose_name='Отчество')
    user_data_birthday = models.DateField(blank=True, null=True, verbose_name='Дата рождения')
    user_location = models.CharField(max_length=100, blank=True, null=True, verbose_name='Страна')
    user_country = models.CharField(max_length=50, blank=True, null=True, verbose_name='Гражданство')
    phoneNumberRegex = RegexValidator(regex=r"^\+?1?\d{8,15}$")  # для валидации
    user_first_phone = PhoneNumberField(unique=True, blank=True, null=True,verbose_name='Мобильный номер')
    user_second_phone = PhoneNumberField(unique=True, blank=True, null=True, verbose_name='Рабочий номер')
    email = models.EmailField(max_length=50, blank=True, null=True, verbose_name='Email')
    education = models.CharField(max_length=200, verbose_name="Высшее учебное заведение")
    user_education = models.CharField(max_length=200, blank=True, null=True, verbose_name='Специальность')
    year_ending = models.DateField(blank=True, null=True, verbose_name='Дата окончания учебы')
    is_created = models.DateTimeField(auto_now_add=True, verbose_name="Создан")

    def __str__(self):
        return str(self.username)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = ' Пользователи'
        ordering = ['is_created']

    @property
    def imageURL(self):
        try:
            url = self.profile_image.url
        except:
            url = ''
        return url

    @property
    def imageURL_border(self):
        try:
            url = self.profile_image_border.url
        except:
            url = ''
        return url

users/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import User, Profile
from django import forms


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'email', 'username', 'password1', 'password2']
        labels = {
            'first_name': 'Name',
            'email': 'email',
            'password1': 'Введите пароль',
            'password2': 'Повторите пароль'
        }

    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['placeholder'] = u'Your name'
        self.fields['username'].widget.attrs['placeholder'] = u'Username'
        self.fields['email'].widget.attrs['placeholder'] = u'Email'
        self.fields['password1'].widget.attrs['placeholder'] = u'Password'
        self.fields['password2'].widget.attrs['placeholder'] = u'Repeat password'
        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})


class ProfileForm(forms.ModelForm):
    profile_image = forms.ImageField(label='Аватарка страницы', required=False, widget=forms.FileInput)
    profile_image_border = forms.ImageField(label='Фон аватарки', required=False, widget=forms.FileInput)

    class Meta:
        model = Profile
        fields = ['name', 'profile_image', 'profile_image_border']
        labels = {
            'name': 'Имя',
            'profile_image': 'Аватарка',
            'profile_image_border': 'Задняя аватарка'
        }

    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)

        for name, field in self.fields.items():
            field.widget.attrs.update({'class': 'input'})

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import CustomUserCreationForm, ProfileForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages


# from .utils import searchProfiles, paginateProfiles


def loginUser(request):
    page = 'login'

    if request.user.is_authenticated:
        pass

    if request.method == 'POST':
        username = request.POST['username'].lower()
        password = request.POST['password']

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'Username does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect(request.GET['next'] if 'next' in request.GET else 'account')

        else:
            messages.error(request, 'Username OR password is incorrect')

    return render(request, 'users/login_register.html')


def logoutUser(request):
    logout(request)
    messages.info(request, 'User was logged out!')
    return redirect('login')


def registerUser(request):
    page = 'register'
    form = CustomUserCreationForm()

    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            user.save()

            messages.success(
                request, 'Пользователь создан!'
            )
            login(request, user)
            return redirect('login')
        else:
            messages.success(
                request, 'Ошибка при создании'
            )
    context = {'page': page, 'form': form}
    return render(request, 'users/login_register.html', context)


@login_required(login_url='login')
def userAccount(request):
    profile = request.user.profile
    context = {'profile': profile}
    return render(request, 'users/althome.html', context)


@login_required(login_url='login')
def homePage(request):
    profile = request.user.profile
    context = {'profile': profile}
    return render(request, 'users/althome.html', context)


@login_required(login_url='login')
def editSettings(request):

    profile = request.user.profile
    form = ProfileForm(instance=profile)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=profile)
        if form.is_valid():
            settings = form.save(commit=False)
            settings.save()
            return redirect('account')

    context = {'form': form, 'profile':profile}
    return render(request, 'users/editSettings.html', context)

templates/althome.html
<!DOCTYPE html>
<html lang="ru" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>home</title>
        <link rel="stylesheet" href="../static/css/master.css">
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <div class="site">
            <header id="header" class="site__header">
                <div class="site__header__wrapper">
                    <a class="site__header__wrapper_content text-CD" href="#">LESSPROFILES</a>
                    <div>
                        <button class="site__header__wrapper_content" id="usernameBtn" type="button" name="button">USERNAME</button>
                        <a class="site__header__wrapper_content hidden" id="settingsBtn" href="settings.html">SETTINGS</a>
                        <a class="site__header__wrapper_content hidden" id="signoutBtn" href="signin.html">SIGN OUT</a>
                    </div>
                </div>
            </header>
            <div class="site__body">
                <div class="site__body__info">
                    <div class="site__body__info__cover">
                        <img class="cover" src="" alt="cvr">
                    </div>
                    <div class="site__body__info__cover-tinted"></div>
                    <div class="site__body__info-left">
                        <div class="site__body__info_picture">
                            <img class="image" src="" alt="img">
                        </div>
                    </div>
                    <div class="site__body__info-right">
                        <div class="site__body__info_name">
                            NAME
                        </div>
                        <div class="site__body__info_username">
                            username
                        </div>
                        <div class="site__body__info__stats">

                        </div>
                    </div>
                </div>
                <div class="site__body__graphql">
                    <div class="site__body__graphql_item"></div>
                    <div class="site__body__graphql_item"></div>
                    <div class="site__body__graphql_item"></div>
                    <div class="site__body__graphql_item"></div>
                    <div class="site__body__graphql_item"></div>
                    <div class="site__body__graphql_item"></div>
                    <div class="site__body__graphql_item"></div>
                    <div class="site__body__graphql_item"></div>
                    <div class="site__body__graphql_item"></div>
                </div>
            </div>
            <footer class="site__footer">
                <div class="site__footer__wrapper">
                    <a class="site__footer__wrapper_content" href="#">INDEX</a>
                    <a class="site__footer__wrapper_content" href="althome.html">HOME</a>
                    <a class="site__footer__wrapper_content" href="settings.html">SETTINGS</a>
                    <a class="site__footer__wrapper_content" href="signin.html">SIGN IN</a>
                    <a class="site__footer__wrapper_content" href="signup.html">SIGN UP</a>
                </div>
            </footer>
        </div>
        <script type="text/javascript">

            const headerNode = document.getElementById('header');

            window.addEventListener('scroll', () => {
                headerNode.classList.toggle('opacity0', window.scrollY <= 380 && window.scrollY > 0 );
                headerNode.classList.toggle('site__header-bg', window.scrollY >= 380);
            });

            const settingsBtnNode = document.getElementById('settingsBtn');

            settingsBtnNode.addEventListener('click', () => {
                settingsBtnNode.classList.toggle('btnActive');
            });

            const usernameBtnNode = document.getElementById('usernameBtn');
            const signoutBtnNode = document.getElementById('signoutBtn');

            usernameBtnNode.addEventListener('click', () => {

                usernameBtnNode.classList.toggle('btnActive');
                settingsBtnNode.classList.toggle('hidden');
                signoutBtnNode.classList.toggle('hidden');

                usernameBtnNode.animate([
                    {opacity: '0'},
                    {opacity: '1'},
                ], 500);
            });

        </script>
    </body>
</html>

templates/header.html
<header class="site__header">
    <div class="site__header__wrapper">
        <a class="site__header__wrapper_content text-CD" href="#">LESSPROFILES</a>
        <div>
            {% if request.user.is_authenticated %}
                <button class="site__header__wrapper_content" id="usernameBtn" type="button" name="button">{{ profile.username }}</button>
                <a class="site__header__wrapper_content btnActive" id="settingsBtn" href="{% url 'edit-account' %}">SETTINGS</a>
                <a class="site__header__wrapper_content hidden" id="signoutBtn" href="{% url 'logout' %}">SIGN OUT</a>
            {% else %}
                <a class="site__header__wrapper_content hidden" id="signoutBtn" href="{% url 'login' %}">SIGN IN</a>
            {% endif %}
        </div>
    </div>
</header>

templates/home.html
<!DOCTYPE html>
<html lang="ru" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>home</title>
        <link rel="stylesheet" href="../static/css/home.css">
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <div class="site">
            <header class="site__header">
                <div class="site__header__wrapper">

                    <a class="site__header__wrapper_content" href="index.html">INDEX</a>
                    <div class="site__header__wrapper_content">HEADER</div>
                    <div class="site__header__wrapper_content">HEADER</div>
                    <div class="site__header__wrapper_content">HEADER</div>
                    <a class="site__header__wrapper_content" href="signin.html">SIGN OUT</a>

                </div>
            </header>
            <div class="site__body">


                <div class="site__body__nav">
                    <div class="site__body__nav_content">NAVIGATION 1</div>
                    <div class="site__body__nav_content">NAVIGATION 2</div>
                    <div class="site__body__nav_content">NAVIGATION 3</div>
                    <div class="site__body__nav_content">NAVIGATION 4</div>
                    <div class="site__body__nav_content">NAVIGATION 5</div>
                </div>
                <div class="site__body__account">
                    <div class="site__body__account_cover">
                        <br>COVER IMAGE HEIGHT=300px
                    </div>
                    <div class="site__body__account_image">
                        <br>...IMAGE...<br>200x200px
                    </div>
                    <div class="site__body__account__information">
                        <div class="site__body__account__information_name">NAME</div>
                        <div class="site__body__account__information_name">NAME</div>
                        <div class="site__body__account__information_name">NAME</div>
                    </div>
                    <div class="site__body__account__content">
                        CONTENT
                    </div>
                </div>


            </div>
            <footer class="site__footer">
                <div class="site__footer__wrapper">

                    <a class="site__footer__wrapper_content" href="index.html">INDEX</a>
                    <a class="site__footer__wrapper_content" href="home.html">HOME</a>
                    <div class="site__footer__wrapper_content"><b>FOOTER</b></div>
                    <a class="site__footer__wrapper_content" href="signin.html">SIGN IN</a>
                    <a class="site__footer__wrapper_content" href="signup.html">SIGN UP</a>

                </div>
            </footer>
        </div>
    </body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="ru" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>index</title>
        <link rel="stylesheet" href="../static/css/style.css">
    </head>
    <body>
        <div class="site">
            <header class="site__header">
                <div class="site__header__wrapper">
                    <div class="site__header__wrapper_content">HEADER</div>
                    <div class="site__header__wrapper_content">HEADER</div>
                    <div class="site__header__wrapper_content">HEADER</div>
                    <div class="site__header__wrapper_content">HEADER</div>
                    <a class="site__header__wrapper_content" href="signin.html">SIGN IN</a>
                </div>
            </header>
            <div class="site__body">
                <div class="site__body__block1">
                    <div class="site__body__block1_content">
                        content
                    </div>
                </div>
                <div class="site__body__block2">
                    <div class="site__body__block2_content">
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
                    </div>
                </div>
                <div class="site__body__block3">
                    <div class="site__body__block3__box">
                        <div class="site__body__block3__box_content">content</div>
                        <div class="site__body__block3__box_content">content</div>
                        <div class="site__body__block3__box_content">content</div>
                        <div class="site__body__block3__box_content">content</div>
                        <div class="site__body__block3__box_content">content</div>
                    </div>
                </div>
            </div>
            <footer class="site__footer">
                <div class="site__footer__wrapper">
                    <a class="site__footer__wrapper_content" href="index.html">INDEX</a>
                    <a class="site__footer__wrapper_content" href="home.html">HOME</a>
                    <div class="site__footer__wrapper_content"><b>FOOTER</b></div>
                    <a class="site__footer__wrapper_content" href="signin.html">SIGN IN</a>
                    <a class="site__footer__wrapper_content" href="signup.html">SIGN UP</a>
                </div>
            </footer>
        </div>
    </body>
</html>

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <!-- Dev Search UI -->
{#    <link rel="stylesheet" href="{% static 'css/home.css' %}" />#}
{#    <link rel="stylesheet" href="{% static 'css/signin.css' %}" />#}
{#    <link rel="stylesheet" href="{% static 'css/signup.css' %}" />#}
{#    <link rel="stylesheet" href="{% static 'css/style.css' %}" />#}
    <link rel="stylesheet" href="{% static 'css/master.css' %}" />

</head>
<body>
{#    {% if messages %}#}
{#    <ul class="messages">#}
{#        {% for message in messages %}#}
{#        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>#}
{#            {% endfor %}#}
{#    </ul>#}
{#    {% endif %} -->#}

    {% if messages %}

    {% for message in messages %}
    <div class="alert  alert--{{message.tags}}">
        <p class="alert__message">{{message}}</p>
        <button class="alert__close">x</button>
    </div>

    {% endfor %}

    {% endif %}
    {% include 'header.html' %}
    {% block content %}

    {% endblock content %}
</body>
<script src="{% static 'uikit/app.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</html>

templates/second_main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="shortcut icon" href="images/favicon.ico" type="image/x-icon" />
    <!-- Icon - IconMonster -->
    <link rel="stylesheet" href="https://cdn.iconmonstr.com/1.3.0/css/iconmonstr-iconic-font.min.css" />
    <!-- Mumble UI -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}" />
    <!-- Dev Search UI -->
    <link rel="stylesheet" href="{% static 'css/home.css' %}" />
{#    <link rel="stylesheet" href="{% static 'css/signin.css' %}" />#}
{#    <link rel="stylesheet" href="{% static 'css/signup.css' %}" />#}
{#    <link rel="stylesheet" href="{% static 'css/style.css' %}" />#}
</head>
<body>
{#    {% if messages %}#}
{#    <ul class="messages">#}
{#        {% for message in messages %}#}
{#        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>#}
{#            {% endfor %}#}
{#    </ul>#}
{#    {% endif %} -->#}

    {% if messages %}

    {% for message in messages %}
    <div class="alert  alert--{{message.tags}}">
        <p class="alert__message">{{message}}</p>
        <button class="alert__close">x</button>
    </div>

    {% endfor %}

    {% endif %}
    {% include 'header.html' %}
    {% block content %}

    {% endblock content %}
</body>
<script src="{% static 'uikit/app.js' %}"></script>
<script src="{% static 'js/main.js' %}"></script>
</html>

templates/signin.html
<!DOCTYPE html>
<html lang="ru" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>sign in</title>
        <link rel="stylesheet" href="../static/css/master.css">
        <meta name="viewport" content="width=device-width">
    </head>
    <body>
        <div class="site">
            <div id="canvas" style="position: absolute; z-index: -1; animation-name: fadein; animation-timing-function: ease-in-out; animation-duration: 7000ms; animation-fill-mode: forwards;"></div>
            <header class="site__header site__header-bg">
                <div class="site__header__wrapper">
                    <a class="site__header__wrapper_content text-CD" href="#">LESSPROFILES</a>
                    <a class="site__header__wrapper_content" href="../users/templates/users/althome.html">HOME</a>
                </div>
            </header>
            <div class="site__body">
                <div class="site__body__signbox-wrapper">
                    <div class="site__body__signbox">
                        <form class="site__body__signbox__form" action="../users/templates/users/althome.html" method="POST">
                            <h3>sign in</h3>
                            <input class="site__body__signbox__form_input" tabindex="1" type="text" name="username" value="" placeholder="username">
                            <input class="site__body__signbox__form_input" tabindex="2" type="password" name="password" value="" placeholder="password">
                            <input class="site__body__signbox__form_button" tabindex="3" type="submit" name="button" value="sign in">
                            <a class="site__body__signbox__form_a" tabindex="4" href="signup.html">Create account</a>
                        </form>
                    </div>
                </div>
            </div>
            <footer class="site__footer">
                <div class="site__footer__wrapper">
                    <a class="site__footer__wrapper_content" href="#">INDEX</a>
                    <a class="site__footer__wrapper_content" href="../users/templates/users/althome.html">HOME</a>
                    <a class="site__footer__wrapper_content" href="settings.html">SETTINGS</a>
                    <a class="site__footer__wrapper_content" href="signin.html">SIGN IN</a>
                    <a class="site__footer__wrapper_content" href="signup.html">SIGN UP</a>
                </div>
            </footer>
        </div>
        <script src="../static/js/canvas.js" charset="utf-8"></script>
    </body>
</html>

users/templates/users/editSettings.html
{% extends 'main.html' %}
{% block content %}

    {#    <div class="site__body__settings_profile-section">#}
    {#        <form class="form" method="POST" action="{% url 'edit-account' %}" enctype="multipart/form-data">#}
    {#            {% csrf_token %}#}
    {#            <div class="form__field">#}
    {##}
    {#                {% for field in form %}#}
    {#                    {{ field }}#}
    {##}
    {#                {% endfor %}#}
    {#            </div>#}
    {#            <input class="site__body__signbox__form_a" style="color: black; padding-right: 22px" type="submit" value="submit"/>#}
    {#        </form>#}
    {#    </div>#}

    <div class="site" xmlns="http://www.w3.org/1999/html">
        <div class="site__body">
            <div class="site__body__info">
                <div class="site__body__info__cover">
                    <img class="cover" src="{{ profile.imageURL_border }}" alt="cvr">
                </div>
                <div class="site__body__info__cover-tinted"></div>
                <div class="site__body__info-left">
                    <div class="site__body__info_picture">
                        <img class="image" src="{{ profile.imageURL }}" alt="img">
                    </div>
                </div>
                <div class="site__body__info-right">
                    <div class="site__body__info_name">
                        {{ profile.name }}
                    </div>
                    <div class="site__body__info_username">
                        {{ profile.username }}
                    </div>
                    <div class="site__body__info__stats">

                    </div>
                </div>
            </div>
            <style>
                input[type='file'] {
                    color: transparent;
                }
            </style>
            <form class="form" method="POST" action="{% url 'edit-account' %}" enctype="multipart/form-data">#}
                {% csrf_token %}#}
                <div class="site__body__settings" id="settingsContainer">
                    <div class="site__body__settings__container">
                        <div class="site__body__settings_heading">
                            Profile settings
                        </div>
                        <div class="site__body__settings_profile-section">
                            <div style="margin-bottom: 5px;">{{ form.name.label }}</div>
                            <label>
                                <input style="margin-top: 5px;" type="text" name="name" value="">
                            </label>
                        </div>
                        <div class="site__body__settings_profile-section">
                            <div style="margin-bottom: 5px;">{{ form.profile_image.label }}</div>
                                                        <input style="display: none;" id="file-input-picture" type="file" name="profile_image" value="">
                            <input style="display: none;" type="file" name="profile_image" accept="image/*" id="id_profile_image">
                            <label style="cursor: pointer; font-size: 22px; font-weight:400;" for="id_profile_image">CHOOSE FILE</label>
                        </div>
                        <div class="site__body__settings_profile-section">
                            <div style="margin-bottom: 5px;">{{ form.profile_image_border.label }}</div>
                            <input style="display: none;" type="file" name="profile_image_border" accept="image/*" id="id_profile_image_border">
                            <label style="cursor: pointer; font-size: 22px; font-weight:400;" for="id_profile_image_border">CHOOSE FILE</label>
                        </div>
{#                        {% for field in form %}#}
{#                            <div class="site__body__settings_profile-section">#}
{#                                {{ field.label }}#}
{#                                {{ field }}#}
{#                            </div>#}
{#                        {% endfor %}#}
                        <input class="site__body__signbox__form_a" tabindex="5" type="submit" name="button" value="Save">
                    </div>
                    <div class="site__body__settings__container">
                        <div class="site__body__settings_heading">
                            Security settings
                        </div>
                        <div class="site__body__integrations">
                            <a class="site__body__signbox__form_a" href="#">settings</a>
                        </div>
                    </div>
                    <div class="site__body__settings__container">
                        <div class="site__body__settings_heading">
                            Integrations
                        </div>
                        <div class="site__body__integrations">
                            <a class="site__body__signbox__form_a" href="#">settings</a>
                        </div>
                    </div>
                </div>
                <a style="margin: 30px auto;" class="site__body__signbox__form_a" href="althome.html">home</a>
            </form>

            <footer class="site__footer">
                <div class="site__footer__wrapper">
                    <a class="site__footer__wrapper_content" href="#">INDEX</a>
                    <a class="site__footer__wrapper_content" href="althome.html">HOME</a>
                    <div class="site__footer__wrapper_content"><b>FOOTER</b></div>
                    <a class="site__footer__wrapper_content" href="signin.html">SIGN IN</a>
                    <a class="site__footer__wrapper_content" href="signup.html">SIGN UP</a>
                </div>
            </footer>
        </div>
    </div>
    <script type="text/javascript">

        const settingsBtnNode = document.getElementById('settingsBtn');
        const settingsContainerNode = document.getElementById('settingsContainer');

        settingsBtnNode.addEventListener('click', () => {
            settingsBtnNode.classList.toggle('btnActive');
        });

        const usernameBtnNode = document.getElementById('usernameBtn');
        const signoutBtnNode = document.getElementById('signoutBtn');

        usernameBtnNode.addEventListener('click', () => {
            usernameBtnNode.classList.toggle('btnActive');
            settingsBtnNode.classList.toggle('hidden');
            signoutBtnNode.classList.toggle('hidden');

            usernameBtnNode.animate([
                {opacity: '0'},
                {opacity: '0.15'},
                {opacity: '0'},
                {opacity: '0.3'},
                {opacity: '0'},
                {opacity: '1'},
            ], 300);
        });

    </script>


{% endblock content %}